### ISSUE TITLE
How to load pretrained correctly ?

### ISSUE THREAD

**Issue by hungdinhxuan** [backspacetg/distilXLSR#1]
Hello @backspacetg,

I see that your code is based on the Fairseq toolkits. I have tried your tutorial by copying codes folder into fairseq/fairseq/models and rename it as distilXLSR. However, it doesn't work well;  I try load pre-trained by common fairseq approach:

`cp_path = 'distilXLSR_xlsr128.pt' `
`model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])`

There are two errors occurred:

1. `ValueError: Dataclass <class 'fairseq.models.distilXLSR.distilxlsr.DistilXLSRConfig'> must extend FairseqDataclass`
Current solution => I have tried by extend FairseqDataclass to DistilXLSRConfig in distilxlsr.py and error 2 occurred

2. `File "/nfs/datab/hungdx/SSL_Anti-spoofing/fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1/fairseq/checkpoint_utils.py", line 419, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/nfs/datab/hungdx/SSL_Anti-spoofing/fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1/fairseq/checkpoint_utils.py", line 337, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/nfs/datab/hungdx/SSL_Anti-spoofing/fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1/fairseq/checkpoint_utils.py", line 573, in _upgrade_state_dict
    {"criterion_name": "CrossEntropyCriterion", "best_loss": state["best_loss"]}
KeyError: 'best_loss'`

I have tried with the recent fairseq version, but it also doesn't work.  Your work I think is precious and it can help me extend my work. Please help me solve my issues. Thank you again for your work.

**Comment by backspacetg** [comment]
Hello, thank you for your interest in our work! Our model is trained in the [S3PRL toolkit](https://github.com/s3prl/s3prl/tree/main/s3prl/pretrain), so the usual fairseq way may not work properly. I have updated the sample codes in the README file, please check there for more details!
Also, I found some bugs in my original code, so please update `distilxlsr_ctc.py` and `distilxlsr.py` in the fairseq folder. Sorry for that!
